import 'package:flutter/material.dart';

const Map<String, Color> colorsAvailable = {
  'white'             : Colors.white,
  'black'             : Colors.black,
  'amber'             : Colors.amber,
  'amberAccent'       : Colors.amberAccent,
  'blue'              : Colors.blue,
  'blueAccent'        : Colors.blueAccent,
  'blueGrey'          : Colors.blueGrey,
  'brown'             : Colors.brown,
  'cyan'              : Colors.cyan,
  'cyanAccent'        : Colors.cyanAccent,
  'deepOrange'        : Colors.deepOrange,
  'deepOrangeAccent'  : Colors.deepOrangeAccent,
  'deepPurple'        : Colors.deepPurple,
  'deepPurpleAccent'  : Colors.deepPurpleAccent,
  'green'             : Colors.green,
  'greenAccent'       : Colors.greenAccent,
  'grey'              : Colors.grey,
  'indigo'            : Colors.indigo,
  'indigoAccent'      : Colors.indigoAccent,
  'lightBlue'         : Colors.lightBlue,
  'lightBlueAccent'   : Colors.lightBlueAccent,
  'lightGreen'        : Colors.lightGreen,
  'lightGreenAccent'  : Colors.lightGreenAccent,
  'lime'              : Colors.lime,
  'limeAccent'        : Colors.limeAccent,
  'orange'            : Colors.orange,
  'orangeAccent'      : Colors.orangeAccent,
  'pink'              : Colors.pink,
  'pinkAccent'        : Colors.pinkAccent,
  'purple'            : Colors.purple,
  'purpleAccent'      : Colors.purpleAccent,
  'red'               : Colors.red,
  'redAccent'         : Colors.redAccent,
  'teal'              : Colors.teal,
  'tealAccent'        : Colors.tealAccent,
  'yellow'            : Colors.yellow,
  'yellowAccent'      : Colors.yellowAccent,
};